#!/usr/bin/env node
/**
 * update-env.js
 * Lit les adresses déployées depuis build/contracts/*.json
 * et met à jour automatiquement frontend/.env
 *
 * Usage : node update-env.js
 */
const fs   = require('fs')
const path = require('path')

const mapping = {
  'Exercice1_Addition': 'VITE_EX1_ADDRESS',
  'Exercice2_Conversion': 'VITE_EX2_ADDRESS',
  'GestionChaines': 'VITE_EX3_ADDRESS',
  'Exercice4_EstPositif': 'VITE_EX4_ADDRESS',
  'Exercice5_Parite': 'VITE_EX5_ADDRESS',
  'Exercice6_Tableau': 'VITE_EX6_ADDRESS',
  'Rectangle': 'VITE_EX7_ADDRESS',
  'Payment': 'VITE_EX8_ADDRESS',
}

const buildDir = path.join(__dirname, 'build', 'contracts')
const envFile  = path.join(__dirname, 'frontend', '.env')

if (!fs.existsSync(buildDir)) {
  console.error('❌  build/contracts not found – run: truffle migrate first')
  process.exit(1)
}

let envContent = '# Auto-generated by update-env.js\n'

for (const [contractName, envKey] of Object.entries(mapping)) {
  const artifactPath = path.join(buildDir, `${contractName}.json`)
  if (!fs.existsSync(artifactPath)) {
    console.warn(`⚠  ${contractName}.json not found – skipping`)
    envContent += `${envKey}=\n`
    continue
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'))
  const networks = artifact.networks || {}
  const keys     = Object.keys(networks)
  if (keys.length === 0) {
    console.warn(`⚠  ${contractName} has no deployed networks`)
    envContent += `${envKey}=\n`
    continue
  }
  // Préférer le réseau 5777 (Ganache) s'il existe, sinon prendre le dernier
  const latestNetwork = networks['5777'] || networks[keys[keys.length - 1]]
  const address = latestNetwork.address || ''
  envContent += `${envKey}=${address}\n`
  console.log(`✅  ${envKey} = ${address}`)
}

fs.writeFileSync(envFile, envContent)
console.log(`\n📝  frontend/.env updated successfully!`)
